from adafruit_servokit import ServoKit
import time

kit = ServoKit(channels=16)

FR_FEMUR_CH = 0
FR_TIBIA_CH = 1

FL_FEMUR_CH = 2
FL_TIBIA_CH = 3

BR_FEMUR_CH = 4
BR_TIBIA_CH = 5

BL_FEMUR_CH = 6   
BL_TIBIA_CH = 7

FR_FEMUR_MIN = 75
FR_FEMUR_MAX = 110
FR_TIBIA_MIN = 65
FR_TIBIA_MAX = 115

FR_NEUTRAL_FEMUR = 90
FR_NEUTRAL_TIBIA = 90

Fl_FEMUR_MIN = 75
Fl_FEMUR_MAX = 110
Fl_TIBIA_MIN = 65
Fl_TIBIA_MAX = 115

Fl_NEUTRAL_FEMUR = 90
Fl_NEUTRAL_TIBIA = 90

BR_FEMUR_MIN = 75
BR_FEMUR_MAX = 110
BR_TIBIA_MIN = 65
BR_TIBIA_MAX = 115

BR_NEUTRAL_FEMUR = 90
BR_NEUTRAL_TIBIA = 90

BL_FEMUR_MIN = 75
BL_FEMUR_MAX = 110
BL_TIBIA_MIN = 65
BL_TIBIA_MAX = 115

BL_NEUTRAL_FEMUR = 90
BL_NEUTRAL_TIBIA = 90

SMOOTH_STEPS = 24
STEP_DELAY = 0.02
SIT_FEMUR_DELTA = +20
SIT_TIBIA_DELTA = +25
LIFT_AMOUNT = 15
FORWARD_DELTA = -10

